### ISSUE TITLE
询问

### ISSUE THREAD

**Issue by zhongly1021** [dingyuan-shi/KDDCup-2020-RL-Track-Champion-Code#1]
您好，请问在阅读您的代码时，代码块：kdtree = pickle.load(open(get_path(__file__, "kdtree"), "rb"))报错为“need more than 7 values to unpack”，不知道您是否知道如何解决呢

**Comment by dingyuan-shi** [comment]
scipy的版本号应该是1.4.1

**Comment by sdycodes** [comment]
> 您好，请问在阅读您的代码时，代码块：kdtree = pickle.load(open(get_path(**file**, "kdtree"), "rb"))报错为“need more than 7 values to unpack”，不知道您是否知道如何解决呢
